# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/asus/7colors/7colors

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/asus/7colors/7colors

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asus/7colors/7colors/CMakeFiles /home/asus/7colors/7colors/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asus/7colors/7colors/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named 7colors

# Build rule for target.
7colors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 7colors
.PHONY : 7colors

# fast build rule for target.
7colors/fast:
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/build
.PHONY : 7colors/fast

board.o: board.c.o

.PHONY : board.o

# target to build an object file
board.c.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/board.c.o
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/board.c.o
.PHONY : board.c.o

board.i: board.c.i

.PHONY : board.i

# target to preprocess a source file
board.c.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/board.c.i
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/board.c.i
.PHONY : board.c.i

board.s: board.c.s

.PHONY : board.s

# target to generate assembly for a file
board.c.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/board.c.s
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/board.c.s
.PHONY : board.c.s

coordinates.o: coordinates.c.o

.PHONY : coordinates.o

# target to build an object file
coordinates.c.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/coordinates.c.o
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/coordinates.c.o
.PHONY : coordinates.c.o

coordinates.i: coordinates.c.i

.PHONY : coordinates.i

# target to preprocess a source file
coordinates.c.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/coordinates.c.i
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/coordinates.c.i
.PHONY : coordinates.c.i

coordinates.s: coordinates.c.s

.PHONY : coordinates.s

# target to generate assembly for a file
coordinates.c.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/coordinates.c.s
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/coordinates.c.s
.PHONY : coordinates.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/main.c.s
.PHONY : main.c.s

player.o: player.c.o

.PHONY : player.o

# target to build an object file
player.c.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/player.c.o
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/player.c.o
.PHONY : player.c.o

player.i: player.c.i

.PHONY : player.i

# target to preprocess a source file
player.c.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/player.c.i
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/player.c.i
.PHONY : player.c.i

player.s: player.c.s

.PHONY : player.s

# target to generate assembly for a file
player.c.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/player.c.s
	$(MAKE) -f CMakeFiles/7colors.dir/build.make CMakeFiles/7colors.dir/player.c.s
.PHONY : player.c.s

tests.o: tests.c.o

.PHONY : tests.o

# target to build an object file
tests.c.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.c.o
.PHONY : tests.c.o

tests.i: tests.c.i

.PHONY : tests.i

# target to preprocess a source file
tests.c.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.c.i
.PHONY : tests.c.i

tests.s: tests.c.s

.PHONY : tests.s

# target to generate assembly for a file
tests.c.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.c.s
.PHONY : tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... tests"
	@echo "... 7colors"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... coordinates.o"
	@echo "... coordinates.i"
	@echo "... coordinates.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

